### ISSUE TITLE
Continuous Integration/ Quality Assurance

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#12]
Hi!

most of the editing of BOT happens directly within the Turtle file using a text editor. However, it happens that typos occur and inconsistent files are uploaded to the github repository.

It might make sense establish an automated way to check a commit on consistency prior to merging it into the master branch. I know Continuous Integration from Travis CI for unit testing in software development projects. Does anyone know if this can be used for OWL2 ontology conformance testing?

Errata: ee04e35aafff196543d2991b9bbe5eed15614a6d should be fine, however the issue is still important.

**Comment by GeorgFerdinandSchneider** [comment]
I came across [LBNL](https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/.travis.yml) who apparently have continuous integration included.

Also a way via OWL API [bibliothek-o](https://github.com/ld4l-labs/bibliotek-o/blob/master/.travis.yml)

**Comment by maximelefrancois86** [comment]
It's on my todo for 2018 ;-)

In the meantime, you can try with http://ontoology.linkeddata.es/  , although it's not a proper CI tool per se.

Max

**Comment by GeorgFerdinandSchneider** [comment]
The [Ontoology](http://ontoology.linkeddata.es/)  sounds good. However, it might be that I do not have enough rights to hook up BOT repository. 

I suggest we keep this as a action item for LDAC 2017 next week.

**Comment by MadsHolten** [comment]
I added a new point to the adding content section of the readme:

3. Validate that the turtle file is still valid using for example Protegé or http://ttl.summerofcode.be/

**Comment by maximelefrancois86** [comment]
Instead of "using Protégé", one may try to load it and validate it using the  OWLAPI java library. That's what Protégé uses.

**Comment by GeorgFerdinandSchneider** [comment]
Should be closed after merge of https://github.com/w3c-lbd-cg/bot/pull/55

**Comment by GeorgFerdinandSchneider** [comment]
closed as of merge of #55
