### ISSUE TITLE
Interface entity

### ISSUE THREAD

**Issue by superlee1** [w3c-lbd-cg/bot#120]
Hi,

the _bot:Interface_ entity is disjointed from _bot:Zone_ and _bot:Element_, i.e., no building element is allowed to "has an interfacing role" connecting other entities. This is conflicted with the comment for _bot:Interface_, giving an example as "A door between one room and another."
How about defining _bot:Interface_ as "anything (incl. surface, physical objects, etc.) that plays an interfacing role", meanwhile removing the disjointness to _bot:Zone_ and _bot:Element_?
Thanks!

**Comment by MadsHolten** [comment]
Hi @superlee1 this would be the wrong way to use BOT interfaces that should in my opinion be kept as disjoint from elements and zones. In the door example the intention would be to have somewhere to describe access restrictions which might be different dependent on the direction you would like to access.

**Comment by superlee1** [comment]
@MadsHolten 
OK! Understood, thanks!
