### ISSUE TITLE
Multilanguage labels for classes and object properties

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#14]
As at LDAC 2017 multilingual guests and speakers participate; we might ask them to provide for classes and object properties labels in multiple languages.

Languages added so far are:

- English ""@en
-  Danish ""@da
- German ""@de
- Italian ""@it
- Dutch ""@nl

Added could be 

- French ""@fr
- ...

More over some of the comments require a revision after the lates release v0.2.0 e.g.

- bot:adjacentElement
- bot:hasSpace

With some of the comments being commented in the current .ttl file

See [BCP47]
A. Phillips; M. Davis. Tags for Identifying Languages. September 2009. IETF Best Current Practice. URL: http://tools.ietf.org/html/bcp47

Or

https://msdn.microsoft.com/en-us/library/ms533052(v=vs.85).aspx

**Comment by MadsHolten** [comment]
@iesnaola added Spanish - thanks for that. We also had workshop participants from Norway, Finland and Sweeden.

- Swedish ""**@sv**
- Norwegian ""**@no**
- Finnish ""**@fi**
