### ISSUE TITLE
Few undeclared annotation properties make BOT not OWL DL

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/bot#15]
When checking BOT with OWLAPI snippet:

``` 
File root = new File("Location of a local repository that contains bot.ttl");
IRI bot = IRI.create("https://w3id.org/bot#");
OWLOntologyManager m = OWLManager.createOWLOntologyManager();
m.getIRIMappers().add(new SimpleIRIMapper(bot, IRI.create(new File(root, "bot.ttl"))));
OWLOntology o = m.loadOntology(bot);
System.out.println("Start check");
OWL2DLProfile profile = new OWL2DLProfile();
OWLProfileReport report = profile.checkOntology(o);
for (OWLProfileViolation v : report.getViolations()) {
    System.out.println(v);
}
```

I get the following violations:

> Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/description> in annotation [Annotation(<http://purl.org/dc/elements/1.1/description> "A simple ontology describing the topology of a building"^^xsd:string) in null]
> Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/title> in annotation [Annotation(<http://purl.org/dc/elements/1.1/title> "BOT"^^xsd:string) in null]
> Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/Language> in annotation [Annotation(<http://purl.org/dc/elements/1.1/Language> "en"^^xsd:string) in null]
> Use of undeclared annotation property: <http://purl.org/dc/elements/1.1/modified> in annotation [Annotation(<http://purl.org/dc/elements/1.1/modified> "October 27th 2017"^^xsd:string) in null]

**Comment by MadsHolten** [comment]
Will you correct these?

**Comment by maximelefrancois86** [comment]
yes :-)
