### ISSUE TITLE
where is the original docs

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/bot#25]
I lost track of where the latest version is:

for the docs:
 here in branch gh-pages vs lbd branch gh-pages

for the ontology
 here in branch master vs lbd branch gh-pages

... is there some code duplication ?

ps. I just updated bot.ttl in this repo master branch

**Comment by MadsHolten** [comment]
This is the source. I will remove bot.ttl from /lbd.

I think we should also host the docs on gh-pages branch here.

**Comment by maximelefrancois86** [comment]
or just have the `gh-pages` branch here ?

**Comment by MadsHolten** [comment]
Exactly. 

Then the docs will be located here: https://w3c-lbd-cg.github.io/bot/

Instead of here: https://w3c-lbd-cg.github.io/lbd/bot/

Right?

**Comment by maximelefrancois86** [comment]
Yes, that's good. Index.html and bot.ttl

**Comment by MadsHolten** [comment]
Docs now moved to this repo. I will update w3id.org and once this is accepted I will close the issue.

I just set the GitHub Pages to read from master instead of gh-pages.

**Comment by MadsHolten** [comment]
All bot content including the docs have now been moved to this repository and w3id.org/bot has been updated.
