### ISSUE TITLE
Elements adjacency

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/bot#26]
elements adjacency currently cannot be represented, but is mentioned in the definition of  an interface

**Comment by MadsHolten** [comment]
My suggestion is that we relax the domain of [bot:adjacentElement](w3id.org/bot#adjacentElement) to only have [schema:domainIncludes](http://meta.schema.org/domainIncludes) that is either a bot:Zone or bot:Element instance.

**Comment by maximelefrancois86** [comment]
Can we think of another solution with less side effects:

- rename `bot:adjacentElement` to `bot:boundedByElement` . In fact, the word "bound" is already part of the definition of this relation: *Relation between a Zone and its adjacent building Element, bounding the Zone.*
- use `bot:adjacentElement` to link elements to elements.

**Comment by maximelefrancois86** [comment]
No resolution on this point during LDAC2018 ?

**Comment by pipauwel** [comment]
LDAC2018: this topic has been postponed. Why do we need adjacency of elements in that sense? Use case?

**Comment by GeorgFerdinandSchneider** [comment]
This issue seems to be outdated. It can be reopened if needed. Adjacency can be expressed in BOT using` bot:adjacentElement`, `bot:adjacentZone`
