### ISSUE TITLE
Opening BOT with Protégé

### ISSUE THREAD

**Issue by iesnaola** [w3c-lbd-cg/bot#28]
Hi,

I cannot open or import the BOT ontology from the links provided with Protégé.  I also tried to download the .ttl file and opening it with Protégé, but the result is the same.

Is anyone else having the same issue?

Iker

**Comment by mathib** [comment]
There seems to be a typo in the BOT.ttl => replace in line 39 the last comma with a semicolon.

If you would run into some similar issues with other turtle data, you can use a turtle validator as https://github.com/IDLabResearch/TurtleValidator

**Comment by iesnaola** [comment]
Thanks @mathib :)

**Comment by MadsHolten** [comment]
Just fixed it. I thought @maximelefrancois86 profound with his QA ;-)
