### ISSUE TITLE
 bot:hasSpace  vs saref4bldg:hasSpace

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c-lbd-cg/bot#3]
domain of bot:hasSpace is a Storey. This is more specific than domain of saref4bldg:hasSpace (which is a building or a building space). if we consider that a storey is a building space, then bot:hasSpace is a sub property of saref4bldg:hasSpace

**Comment by GeorgFerdinandSchneider** [comment]
Hi Maxime!

thanks for mentioning this. I agree on your view.

maybe it also makes sense to add to the BOT SAREF4BLDG alignment the following statement

>bot:Storey rdfs:SubClassOf s4bldg:BuildingSpace . 

Best

Georg

**Comment by pipauwel** [comment]
There might be a possible mismatch in the alignment:

>bot:Storey rdfs:SubClassOf s4bldg:BuildingSpace .
>s4bldg:BuildingSpace owl:equivalentClass bot:Space .

**Possible remedies**
1.  Relax the domain of the hasSpace relation.

2. not include:
>bot:Storey rdfs:SubClassOf s4bldg:BuildingSpace .

**Comment by GeorgFerdinandSchneider** [comment]
This should be resolved with the new revision. Revision required on LDAC2017 to ensure semantic correctness with novel domain restrictions on `bot:hasSpace`

**Comment by GeorgFerdinandSchneider** [comment]
@MadsHolten: As the domain restrictions has been relaxed, I suggest to close this issue
