### ISSUE TITLE
superproperty for bot:containsZone and bot:adjacentZone - bot:hasZone

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/bot#30]
Similarly as the new `bot:hasElement` (superprop of  `bot:adjacentElement` and `bot:containsElement`), there should probably also be a `bot:hasZone` superprop for `bot:adjacentZone` and `bot:containsZone`?

**Comment by stickxxx** [comment]
I would agree. And the definition of this new superprop should be similar to the one Mads just suggested for bot:hasElement (e.g. not to be stated explicitly but inferred).

**Comment by MadsHolten** [comment]
I would like to see a use case for it first as I cannot think of any.

**Comment by stickxxx** [comment]
I was agreeing in the sense that it is coherent with the other superprop. So just for the sake of coherence ;)

**Comment by mathib** [comment]
This `bot:hasZone` relation could be used between a stairwell space and the storeys it intersects with? But it could be problematic e.g. if you have a space adjacent to another space belonging to another building. If you then would query for all `bot:hasZone` of the first building, the adjacent space of another building will be included. 

Maybe it's better to have another property on the same level as `bot:adjacentZone` and `bot:containsZone` but for intersecting zones, e.g. `bot:intersectingZone`. I would like a similar property for elements, e.g. `bot:intersectingElement` for elements that intersect multiple zones. This because the 'contains' and 'adjacent' relations expect an element/zone to be completely contained or adjacent in another zone

**Comment by maximelefrancois86** [comment]
Could `bot:intersectingElement` be defined a a sub-property of both `bot:adjacentZone` and `bot:containsZone` ?

Consider the following simple use case:

![bim1](https://user-images.githubusercontent.com/11416248/41655809-61dd3de6-748e-11e8-912a-c52f4d55da45.png)

Which of the following statement(s) is (are) true:

1. Element 1 is contained in both zones
2. Element 1 is adjacent to both zones
3. Element 1 intersects both zones

```
<zoneA> bot:intersectingElement <element1> .
<zoneB> bot:intersectingElement <element1> .
``` 

- Can you imagin a configuration where intersection does not imply contained ?
- Can you imagin a configuration where intersection does not imply adjacent ?

**Comment by maximelefrancois86** [comment]
Here are the proposals we discussed today at LDAC about new properties to link zones and zones, and zones and elements:

# new property partlyContainsZone

![bot2](https://user-images.githubusercontent.com/11416248/41660757-403c27a6-749d-11e8-931a-dbf00b6e98c5.png)

# new property partlyContainsElement

![bot1](https://user-images.githubusercontent.com/11416248/41660750-3e170d42-749d-11e8-9ae4-419a4b2dd8d2.png)

**Comment by maximelefrancois86** [comment]
proposal: introducing partlyContainsElement and partlyContainsZone

**Comment by pipauwel** [comment]
LDAC2018: potentially take inspiration from: https://en.wikipedia.org/wiki/Region_connection_calculus

**Comment by maximelefrancois86** [comment]
contains, overlaps, adjacent, are just simple enough to be used without errors !

**Comment by pipauwel** [comment]
LDAC2018: added properties

bot:hasIntersectingElement and bot:intersectsZone

We should consider disjointness between bot:hasIntersectingElement, adjacentElement, and containsElement (not added now)

**Comment by GeorgFerdinandSchneider** [comment]
This discussion seems to be ended. It can be reopened if needed, e.g. when considering it vor v 0.4.0
