### ISSUE TITLE
Check and merge revised alignments to BRICK and S4Bldg

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#35]
Dear all!

in the branch the SAREF4BUILDINGAlignment ontology and the BRICKAlignment ontology are revised to fit the novel semantics of the latest BOT ontology.

The branch needs to be synchronised with the master branch with the changes to the documentation and the BOT ontology. Then it can be merged. I would need some git support for handling this sync and merge.

Thanks!

**Comment by maximelefrancois86** [comment]
I'll help you to do this tomorrow

**Comment by GeorgFerdinandSchneider** [comment]
Great!

While LDAC 2018 participants are walking through the issues it would be great if participants can discuss the proposed alignmnets [BRANCH](https://github.com/w3c-lbd-cg/bot/tree/revisingAlignments)

**Comment by GeorgFerdinandSchneider** [comment]
Closed by https://github.com/w3c-lbd-cg/bot/commit/e9e6e34a3560d97fff02d78094b040652745fa5d
