### ISSUE TITLE
Difference between bot Zone and bot Space

### ISSUE THREAD

**Issue by kmcglinn** [w3c-lbd-cg/bot#38]
Hi All,

I was hoping you could clear up something for me. I have been looking over BOT and I was wondering how the concept of Space is being used? 

The documentation says: Spaces may be contained in storeys, buildings, and construction sites and Spaces may intersect different storeys, buildings, and construction sites.

I see that a Storey hasSpace Space, am I correct in assuming this does not imply a contains relationship? What is the difference then between a space and a zone? 

Kris.

**Comment by MadsHolten** [comment]
Hi Kris,

A [bot:Zone](https://w3c-lbd-cg.github.io/bot/#Zone) was revised after LDAC 2018 and is now described in the following way:

> A spatial 3D division. Sub-classes of bot:Zone include bot:Site, bot:Building, bot:Storey, or bot:Space. An instance of bot:Zone can contain other bot:Zone instances, making it possible to group or subdivide zones. An instance of bot:Zone can be adjacent to other bot:Zone instances. Finally, a bot:Zone can instantiate two relations to bot:Element, which are either contained in (bot:containsElement), or adjacent to it (bot:adjacentElement).

A [bot:Space](https://w3c-lbd-cg.github.io/bot/#Space) is a sub-class of a bot:Zone and is currently defined as:

> A limited three-dimensional extent defined physically or notionally [ISO 12006-2 (DIS 2013), 3.4.3]. 

bot:Zones can basically be any spatial 3D division that you need to describe. A bot:Space could contain two bot:Zones that describe requirements for lighting for instance and several bot:Spaces can also be grouped into a bot:Zone describing a fire cell.

Does this answer your question?

**Comment by kmcglinn** [comment]
Hi Mads,

Thanks for getting back to me on this. 

Firstly, I do not have access to the full documentation for ISO 12006-2. It seems you have to pay for it, unless you have a link? Going from the definitions you give though, I am still not sure if they help to answer my question. Doesn't a 3D division imply some limited extent? 

Best,

Kris.

**Comment by mathib** [comment]
> I see that a Storey hasSpace Space, am I correct in assuming this does not imply a contains relationship? What is the difference then between a space and a zone?

A `bot:hasSpace` is a subproperty of `bot:containsZone`. A zone is more generic then a space, as a zone can be a site, building, storey or space, or a grouping of multiple zones, or a part of another zone.

I think the space definition is maybe quite short at the moment, but it should be something that is closer to what we in regular life define as a space/room. Note that a zone (and thus also a `bot:Space`) can also exist notionally, e.g. for defining client requirements for the zone without having to create/design a zone with a certain geometry

**Comment by kmcglinn** [comment]
Hi Mads,

Yeah, I agree. I think you mentioned that in LDAC2018, about Space being closer to a room. That is why I was not sure about any implied containment within the current definition. 

Perhaps number 11 of the competency questions also needs to be revised then?

Best,

Kris.

**Comment by deKlerk** [comment]
Note from LDAC2019: Zone is defined in BOT as "A spatial 3D division" (see full definition in https://w3c-lbd-cg.github.io/bot/#Zone). There are many other definitions in the industry of the term Zone. The bot:Zone can be used for most of those uses.

We need to update the definition of bot:Site: the definition includes the term "Area", but a site is 3Dimensional. 

Topic can be closed.

**Comment by GeorgFerdinandSchneider** [comment]
the definition of bot:Site is changed as of #54 hence this issue can be closed. Remaining discussion in #54
