### ISSUE TITLE
Problems importing BOT

### ISSUE THREAD

**Issue by iesnaola** [w3c-lbd-cg/bot#39]
Hi,

I am still having troubles reusing the BOT ontology. I tried importing the ontology in Protègè but it seems there is some problem. I with both "http://www.w3id.org/bot/bot.ttl" and "http://www.w3id.org/bot" URLs. 

When I try to load the ontology, I get the following Load Error:
 _sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_

How can I deal with this problem? Is there another way I can reuse the BOT ontology?

Thanks,
Iker

**Comment by maximelefrancois86** [comment]
Hi Iker,
Just try with https instead
Best
Max

**Comment by iesnaola** [comment]
Hi Maxime,

Thanks for your response. The importation works for the URL "https://raw.githubusercontent.com/w3c-lbd-cg/bot/master/bot.ttl".

However, once I save the ontology and try to open it again, it seems BOT cannot be correctly loaded.

![Proègè Error](https://image.ibb.co/jhMM68/load_Error.png)

Iker

**Comment by MadsHolten** [comment]
Hi Iker. Have you tried importing from [w3id.org/bot/bot.ttl](w3id.org/bot/bot.ttl) ([https://w3c-lbd-cg.github.io/bot/bot.ttl](https://w3c-lbd-cg.github.io/bot/bot.ttl))?

**Comment by iesnaola** [comment]
Hi Mads,

Thanks for your help. It seems this last URL you wrote works. However, there is a minor issue that happens when the Ontology (which imports the BOT ontology) is closed, and opened in the future. It is related to the "Ontology IRI" and "Location" of the Direct Import, which seem to be switched. The  As I said, it is just a minor issue so I will deal with that, but just for you to know.

When the BOT ontology is imported:
![Proègè Error](https://image.ibb.co/kMW8oK/bot_import.png)

When the ontology where BOT is imported is closed and opened 
![Proègè Error](https://image.ibb.co/j5cnhe/import_reopen.png)

**Comment by mathib** [comment]
Apparently, it was an issue with Protégé: https://github.com/perma-id/w3id.org/pull/1384
It is solved in v5.5. I tested to load FOG (https://w3id.org/fog#) which works now. BOT cannot be loaded however from https://w3id.org/bot# (it works from https://w3id.org/bot/bot.ttl): `org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=2:column=17] Expecting rdf:RDF element.`

**Comment by AnnaWagner** [comment]
I just updated the htaccess of BOT while I was fixing my own redirects. As soon as the merge request goes through, it should be possible to import BOT on the fly from Protégé. 
Also, I noticed BOT is only available in TTL serialisation - maybe you want to extend that to RDF, JSON-LD and N-Triples? The according rewrite rules are already in the htaccess. 
You can by the way additionally create rewrite rules for previous versions of the ontology so that https://w3id.org/bot/0.0.1 would direct you to the file/documentation of that version, if you provide that online as well.

**Comment by GeorgFerdinandSchneider** [comment]
The content is accessible through a browser. We are not sure but as other ontologies are affected this seems to be a problem of protege
