### ISSUE TITLE
Links to BOT draft are wrong in latest meeting minutes (4 June 2018)

### ISSUE THREAD

**Issue by simonstey** [w3c-lbd-cg/bot#40]
[From 4 June 2018 (16:00 CET) telco meeting minutes](https://docs.google.com/document/d/1SXjROsqGqyL6bbnUIHCLbSmeBhBU29HNftCEy-vEcfM/) (just one example): 
> [Documentation] First draft initiated: https://w3c-lbd-cg.github.io/lbd/bot/

while it should be https://w3c-lbd-cg.github.io/bot/ 

-- simon

**Comment by pipauwel** [comment]
Thank you - resolved wrong links in the 4 June doc - the namespace changed in June/July.
