### ISSUE TITLE
HTTP vs HTTPS in namespace

### ISSUE THREAD

**Issue by vcharpenay** [w3c-lbd-cg/bot#42]
On the HTML documentation, the namespace is defined as ` http://www.w3id.org/bot#`. In the Turtle file, however, the prefix declaration is with an HTTPS URL instead: `@prefix bot: <https://w3id.org/bot#>`. (This URL is also without `www.`.)

**Comment by MadsHolten** [comment]
Thanks for the notification. I will update the HTML documentation. HTTPS is also used by prefix.cc/bot

**Comment by MadsHolten** [comment]
Fixed.
