### ISSUE TITLE
Problem with ontology IRI and bot namespace

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#44]
Their  might be a bug/ implementation error of BOT regarding its entity IRI and namespace

The entity is specified by the triple:
```turtle
<https://w3id.org/bot#> rdf:type owl:Ontology .
```
Where there is no difference to the namespace:
```turtle
@prefix bot: <https://w3id.org/bot#> .
```
I propose to change the entity IRI to the following (cf. also https://www.w3.org/TR/owl2-primer/, Section 8.2):

```turtle
<https://w3id.org/bot> rdf:type owl:Ontology .
```

Probably this is causing also the problem with #39.

Best

Georg

**Comment by GeorgFerdinandSchneider** [comment]
Implemented change in 7fc7b1efd2eed45370275203dcb5f5c0c8f732ad in branch  issue44_ontologyEntityNaming

**Comment by maximelefrancois86** [comment]
Hi Georg. 

The namespace si not a resource per se (identified by a URI). It's not a problem if the URI of the namespace is the same as the URI of the ontology.

However, there are implications if the ontology URI does not end with a local identifier:  If you look up the ontology URI (which has no hash), and you get a 200 OK, then the URI identifies the document that you retrieve. So the document = the ontology. This is not OK.

This is why there are two approaches:  (1) use a hash URI  or (2) have a 303 redirection in the chain of redirections to the ontology document. 

The initial choice was option (1), purposely. It's not a typo, nor an error.

Note that the BOT URI is a w3id.org URI. So technically it is also possible to implement option (2).

One comment that can help us settle on this is: Cool URIs don't change. So as the URI was ending with a hash, let it stay that way ;-)

**Comment by GeorgFerdinandSchneider** [comment]
Hi Max!

thanks for the clarification! So I will discard the  issue44_ontologyEntityNaming branch.

However, I will have to correct in the Alignments branch as I used the 

```turtle
xxxx owl:imports <https://w3id.org/bot> .
```

**Comment by GeorgFerdinandSchneider** [comment]
closed()
