### ISSUE TITLE
Update definition of hasSubElement

### ISSUE THREAD

**Issue by deKlerk** [w3c-lbd-cg/bot#47]
The definition of the property bot:hasSubElement needs to be updated. It now still has the older definition:

hosts element - Relation between an element a) and another element b) hosted by element a).

**Comment by deKlerk** [comment]
Note from LDAC2019:
The hasSubElement property covers all subcomposition and aggregation (e.g. hosts). It can and should be defined as a Transitive Property.

**Comment by GeorgFerdinandSchneider** [comment]
Current definition is "Relation between an element a) and another element b) hosted by element a)"

**Comment by mathib** [comment]
Current definition (v0.3.1):

> Relation between an element a) and another element b) hosted by element a)

Proposal:

>Relation between two building elements, either one element hosting another (e.g. a window hosted by a wall) or a subcomposition of a building element into smaller parts (e.g. a fan as part of an air handling unit).

**Comment by GeorgFerdinandSchneider** [comment]
+1

**Comment by maximelefrancois86** [comment]
agreed

**Comment by mathib** [comment]
> Note from LDAC2019:
> The hasSubElement property covers all subcomposition and aggregation (e.g. hosts). It can and should be defined as a Transitive Property.

Just noticed that `bot:hasSubElement` is not yet defined as being transitive. 

In addition, the following additional property chain axiom might be beneficial and correct on `bot:containsElement`:

`owl:propertyChainAxiom ( bot:containsElement bot:hasSubElement )`

**Comment by GeorgFerdinandSchneider** [comment]
Sounds good, should be in a upcoming version of BOT e.g. 0.4.0 or 1.0.0

**Comment by maximelefrancois86** [comment]
Before integrating these two new axioms (transitivity and property chain axiom, please check that we remain in OWL 2 DL (global restriction: total order on non-simple properties https://www.w3.org/TR/owl2-syntax/#Property_Hierarchy_and_Simple_Object_Property_Expressions )  check with owlapi, maybe https://github.com/stain/profilechecker

**Comment by GeorgFerdinandSchneider** [comment]
The definition has been accepted as of [W3C LBD CG TelCo 19 May 2020](https://docs.google.com/document/d/1Oi8zgtcfxyzE0c0Mfd0C2uiedl483flY_WbErHbPSes/edit#)

> Relation between two building elements, either one element hosting another (e.g. a window hosted by a wall) or a subcomposition of a building element into smaller parts (e.g. a fan as part of an air handling unit).

The addition of logical statements as mentioned above https://github.com/w3c-lbd-cg/bot/issues/47#issuecomment-621215340 is postponed until future revisions of BOT -> https://github.com/w3c-lbd-cg/bot/issues/74

**Comment by GeorgFerdinandSchneider** [comment]
Comment received by @deKlerk through comment on [google spreadshee](https://docs.google.com/spreadsheets/d/1J5mEyblGU0M57XNpwQWxHbGlilRMzmCEqoU5FmOHILE/edit#gid=0)t:

> the examples in the description actually describe the inverse relation of bot:hasSubElement ;)
they should be used to describe the (non existent) property bot:subElementOf instead

Current:

> Relation between two building elements, either one element hosting another (e.g. a window hosted by a wall) or a subcomposition of a building element into smaller parts (e.g. a fan as part of an air handling unit).

Proposal:

> Relation between two building elements, either one element hosting another (e.g. a wall hosts a window) or a subcomposition of a building element into smaller parts (e.g. an air handling unit has as a part a fan).

**Comment by GeorgFerdinandSchneider** [comment]
-> Should be changed

**Comment by GeorgFerdinandSchneider** [comment]
Change the description as proposed by @deKlerk accepted [W3c LBD CG meeting on 28 July 2020](https://docs.google.com/document/d/1vGWEwbvVk0wa9JaBJtUMqWqckfa2lASVcr1swsBIR-I/edit#) (Flipping around the examples in "e.g.")

issue with property chain propose by @mathib remains -> v0.4.0 cf. [above](https://github.com/w3c-lbd-cg/bot/issues/47#issuecomment-633024839)

**Comment by GeorgFerdinandSchneider** [comment]
closed by https://github.com/w3c-lbd-cg/bot/commit/a460732116ae06ebaac8f960b2228f355f28685a
