### ISSUE TITLE
LOV entry outdated

### ISSUE THREAD

**Issue by AnnaWagner** [w3c-lbd-cg/bot#48]
The current LOV entry for BOT is for BOT v0.2.0 and needs updating.
See https://lov.linkeddata.es/dataset/lov/vocabs/bto

**Comment by GeorgFerdinandSchneider** [comment]
Will be changed with the help of @mariapoveda as soon as changes to bot v0.3.2 are made

**Comment by mariapoveda** [comment]
Which fields need to be updated?

**Comment by GeorgFerdinandSchneider** [comment]
Thank you @mariapoveda for taking care of the update.

Please update:

homepage: https://w3c-lbd-cg.github.io/bot/index.html

Description: if possible everything in dcterms:description in [bot-0.3.2.ttl](https://github.com/w3c-lbd-cg/bot/blob/master/bot.ttl)

languages: as in [bot-0.3.2.ttl](https://github.com/w3c-lbd-cg/bot/blob/master/bot.ttl)

Creators: as in [bot-0.3.2.ttl](https://github.com/w3c-lbd-cg/bot/blob/master/bot.ttl)

Contributors: as in [bot-0.3.2.ttl](https://github.com/w3c-lbd-cg/bot/blob/master/bot.ttl)

comment: Please cite paper in SWJ: BOT: the Building Topology Ontology of the W3C Linked Building Data Group. Mads Holten Rasmussen; Maxime Lefrançois; Georg Ferdinand Schneider; Pieter Pauwels. Semantic Web Journal, IOS Press, 2020, Accepted. URL: http://www.semantic-web-journal.net/system/files/swj2279.pdf


If possible the LOV IRI could be changed from https://lov.linkeddata.es/dataset/lov/vocabs/bto to https://lov.linkeddata.es/dataset/lov/vocabs/bot

**Comment by mariapoveda** [comment]
Please update:

homepage: https://w3c-lbd-cg.github.io/bot/index.html

**Done**

Description: if possible everything in dcterms:description in bot-0.3.2.ttl

**Done**

languages: as in bot-0.3.2.ttl

**Done**: should be reflected when the new version is indexed (see the version history at the end of the page)

Creators: as in bot-0.3.2.ttl

**Done**

Contributors: as in bot-0.3.2.ttl

**Done** for those contributors that are already included in LOV, for the rest a URI is needed for each one

comment: Please cite paper in SWJ: BOT: the Building Topology Ontology of the W3C Linked Building Data Group. Mads Holten Rasmussen; Maxime Lefrançois; Georg Ferdinand Schneider; Pieter Pauwels. Semantic Web Journal, IOS Press, 2020, Accepted. URL: http://www.semantic-web-journal.net/system/files/swj2279.pdf

**Done**

If possible the LOV IRI could be changed from https://lov.linkeddata.es/dataset/lov/vocabs/bto to https://lov.linkeddata.es/dataset/lov/vocabs/bot

Not possible as the other URI is already taken (see https://lov.linkeddata.es/dataset/lov/vocabs/bot) 2 vocabs can't take the same prefix.

**Comment by GeorgFerdinandSchneider** [comment]
Thanks @mariapoveda ! I think so far this is great. I will ask contributors who like to be added in LOV for their IRI.

**Comment by GeorgFerdinandSchneider** [comment]
To be added:

<http://orcid.org/0000-0002-6930-8543> a vcard:Individual , schema:Person;
        vcard:fn    "Rui de Klerk" ;
        schema:name "Rui de Klerk" .

<https://orcid.org/0000-0001-9841-0494> a vcard:Individual , schema:Person;
        vcard:fn    "Ana Roxin" ;
        schema:name "Ana Roxin" .

**Comment by mariapoveda** [comment]
Rui de Klerk andd Ana Roxin added: https://lov.linkeddata.es/dataset/lov/vocabs/bto

**Comment by ruirzma** [comment]
https://www.researchgate.net/profile/Rui_Ma80 a vcard:Individual , schema:Person;
vcard:fn "Rui Ma" ;
schema:name "Rui Ma" .

**Comment by mariapoveda** [comment]
added

**Comment by hammar** [comment]
<https://karlhammar.com> a vcard:Individual , schema:Person; 
        vcard:fn    "Karl Hammar" ;
        schema:name    "Karl Hammar" .

Thank you!

**Comment by mariapoveda** [comment]
done!

**Comment by HervePruvost** [comment]
<https://orcid.org/0000-0001-7604-8543> a vcard:Individual , schema:Person; 
	vcard:fn    "Hervé Pruvost" ;
	schema:name "Hervé Pruvost" .

Thank you

**Comment by mariapoveda** [comment]
added! https://lov.linkeddata.es/dataset/lov/vocabs/bto

**Comment by k-breitenfelder** [comment]
https://www.linkedin.com/in/katjabreitenfelder a vcard:Individual , schema:Person;
vcard:fn "Katja Breitenfelder" ;
schema:name "Katja Breitenfelder" .

Thank you, Maria! if not submitted too late

**Comment by mariapoveda** [comment]
added!

**Comment by GeorgFerdinandSchneider** [comment]
We might close this issue now. 

A great thank you @mariapoveda for your help! The new entry looks great!
