### ISSUE TITLE
Mistake in BRICK Alignment Section

### ISSUE THREAD

**Issue by iesnaola** [w3c-lbd-cg/bot#56]
Hi,

I think there is a mistake in BOT's HTML version within the section **4.1 BRICK Alignment Module**. It says _"The following namespace prefixes are used in the alignment to SOSA and SSN"_. Furthermore, there is a class alignment that it looks like it was borrwed from SOSA/SSN's page?

Just for your information.

Best regards,
Iker

**Comment by GeorgFerdinandSchneider** [comment]
Hi Iker! Thanks for pointing to this bug.

I removed it by https://github.com/w3c-lbd-cg/bot/pull/57

Best!
