### ISSUE TITLE
Multi-language update fo description and labels

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#64]
Some of the multi-language language labels have become updated after revisions of BOT

Supposed to be updated and a collection effort is running here:

https://docs.google.com/spreadsheets/d/1J5mEyblGU0M57XNpwQWxHbGlilRMzmCEqoU5FmOHILE/edit#gid=0

SPARQL query to filter bot concepts and properties with their language comments and labels from your local triple store:

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
select ?s ?lab ?des
where { 
    BIND( 'cn' AS ?lang )
	{?s rdf:type owl:Class .
    OPTIONAL{
    	?s rdfs:comment ?des .
    	?s rdfs:label ?lab. 
    	FILTER (lang(?des) = ?lang )
        FILTER (lang(?lab) = ?lang )
        }
    }
    UNION
    {?s rdf:type owl:ObjectProperty .
    OPTIONAL{
        ?s rdfs:comment ?des .
    	?s rdfs:label ?lab
    	FILTER (lang(?des) = ?lang)
    	FILTER (lang(?lab) = ?lang)    
        }
    }
    UNION
    {?s rdf:type owl:DatatypeProperty .
        OPTIONAL{
    ?s rdfs:comment ?des .
    ?s rdfs:label ?lab
    FILTER (lang(?des) = ?lang)
    FILTER (lang(?lab) = ?lang)
        }
    }
FILTER( STRSTARTS( STR( ?s ), "https://w3id.org/bot#"))
}
```

**Comment by mathib** [comment]
isn't it a better idea to share the editable link to the spreadsheet in the internal mailinglist only, to avoid unwanted changes by other, external people? Otherwise, great initiative!

**Comment by GeorgFerdinandSchneider** [comment]
For now we leave it open for every one to edit easily. We need to perform a disclosed revision by nominated editors prior to adding new language labels to BOT.

**Comment by GeorgFerdinandSchneider** [comment]
Corresponding PR is https://github.com/w3c-lbd-cg/bot/pull/73

**Comment by GeorgFerdinandSchneider** [comment]
Links to #90 #88 #87 #47 

Current work item is branch 

feature_multiLanguageLabels

**Comment by GeorgFerdinandSchneider** [comment]
closed by https://github.com/w3c-lbd-cg/bot/commit/a460732116ae06ebaac8f960b2228f355f28685a
