### ISSUE TITLE
update definition of bot:Building

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/bot#65]
Similar as https://github.com/w3c-lbd-cg/bot/issues/54 for `bot:Site`, the definition of `bot:Building` should be updated to reflect that it considers something that has a spatial 3D extent.

Definition in v0.3.1

>An independent unit of the built environment with a characteristic spatial structure, intended to serve at least one function or user activity [ISO 12006-2:2013]

 Proposal:
> An independent unit of the built environment with a characteristic spatial structure, intended to serve at least one function or user activity [ISO 12006-2:2013]. A bot:Building is a part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, is contained in a building site, and can contain one or more storeys that are vertically connected.

**Comment by GeorgFerdinandSchneider** [comment]
+1

**Comment by maximelefrancois86** [comment]
+1, looks good to me

**Comment by GeorgFerdinandSchneider** [comment]
As above but accepted in W3C LBD CG call on 19/05/2020:

> An independent unit of the built environment with a characteristic spatial structure, intended to serve at least one function or user activity [ISO 12006-2:2013]. A bot:Building is a part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, is contained in a building site, and can contain one or more storeys that are vertically connected.

**Comment by mathib** [comment]
> An independent unit of the built environment with a characteristic spatial structure, intended to serve at least one function or user activity [ISO 12006-2:2013]. A bot:Building is a part of ...

An open question to the community: is this definition rigid enough, even if it comes partially from a standard? To my feeling, it does not clearly separate buildings from [other man-made constructions](https://en.wikipedia.org/wiki/List_of_nonbuilding_structure_types) such as infrastructure (bridges, tunnels, docks, railroads, roads, dams, etc.), mines, pure storage spaces (granaries, oil tanks, gas tanks, etc.), etc.

I'm asking since I'm preparing a taxonomy with specializations of `bot:Building` based on an existing taxonomy of constructions. I was thinking that the following might be useful to add:
* man-made construction
* construction that can be entered by a man, i.e. having walls and a roof
* protects people or things from the environment (wind, rain, sun, etc.)
* permanent (e.g. excluding tents and other temporary constructions)

Some examples of English dictionary entries for building:
* "a usually roofed and walled structure built for permanent use (as for a dwelling)" [merriam-webster](https://www.merriam-webster.com/dictionary/building)
* "a structure with walls and a roof, such as a house or factory, to give protection to people, animals, or things" [Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/building)

Maybe some other construction-related standards might describe the term "building" better?

P.S. small note: the ISO 12006-2 in the current definition is from 2015, not 2013
