### ISSUE TITLE
update definition of bot:Storey

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/bot#66]
Similar as https://github.com/w3c-lbd-cg/bot/issues/54 for `bot:Site`, the definition of `bot:Storey` should be updated to reflect that it considers something that has a spatial 3D extent.

Current v0.3.1:
>A level part of a building

Proposal:
> A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, is contained by one or more buildings, and is intended to contain one or more spaces that are horizontally connected. Storeys of a building are connected by means of vertical connections such as elevators and stairs.

I added the line "contained by a one or more buildings", to describe situations where you have multiple buildings that are connected via e.g. a shared garage as a storey.

We might need to add a line to avoid ambiguity such as exists in natural language: "storey" vs "floor" (and maybe "level" from as used by Revit to denote storeys)? => this was discussed in a LBD call, but I don't know if it was resolved back then.. Proposal for addition:

> A bot:Storey is not limited to the meaning of "floor" or "level" as exists in natural language: it encompasses both zones above and below ground.

**Comment by GeorgFerdinandSchneider** [comment]
+1

In particular I am in favor of the sentence to clarify the relation to floor and level.

The ambiguity for "floor" and "level" might reside only in american vs. british english or only in english language. Hence instead of describing level and floor I´d  propose to change the description to what the term refers to:

>A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent, is contained by one or more buildings, and is intended to contain one or more spaces that are horizontally connected. Storeys of a building are connected by means of vertical connections such as elevators and stairs. A bot:Storey encompasses both zones above and below ground.

An example by @RichardPinka could be helpful to clarify the broader meaning of BOT
>'A Building with 21 floors, one ground floor and 3 basements' is equal to the sentence: 'A Building has 25 `bot:Storey`s'

**Comment by maximelefrancois86** [comment]
I agree with both comments

**Comment by GeorgFerdinandSchneider** [comment]
Summarizing the above and some text cleaning:

>A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent. A bot:Storey is contained in one or more buildings, and is intended to contain one or more spaces that are horizontally connected. Storeys of a building are connected by means of vertical connections such as elevators and stairs. A bot:Storey encompasses both zones above and below ground, for example,  a building <buiA> with 21 floors, one ground floor and 3 basements' is equal to the sentence: '<buiA> has 25 bot:Storeys'.

**Comment by GeorgFerdinandSchneider** [comment]
by @mathib :

This looks good to me. I only have a small comment on the bot:Storey example at the end of the definition: <buiA> has 25 bot:Storeys'.
It resembles a triple structure, but it is not, right? Maybe better to just write this in natural language as follows:
"...a building A with 21 floors above ground, one ground floor and 3 basements is equal to the sentence: building A has 25 instances of bot:Storey."

**Comment by GeorgFerdinandSchneider** [comment]
Proposal accepted by [W3C LBD CG TelCo as of 19 May 2020](https://docs.google.com/document/d/1Oi8zgtcfxyzE0c0Mfd0C2uiedl483flY_WbErHbPSes/edit#)

> A part of the physical world or a virtual world that is inherently both located in this world and having a 3D spatial extent. A bot:Storey is contained in one or more buildings, and is intended to contain one or more spaces that are horizontally connected. Storeys of a building are connected by means of vertical connections such as elevators and stairs. A bot:Storey encompasses both zones above and below ground, for example, a building with 21 floors above ground, one ground floor and 3 basements is equal to the sentence: A building has 25 instances of bot:Storey.
