### ISSUE TITLE
update definition of bot:interfaceOf

### ISSUE THREAD

**Issue by mathib** [w3c-lbd-cg/bot#67]
`bot:interfaceOf` has no `rdfs:range` or `schema:rangeIncludes` defined, while the definition states:

> Relationship between an interface and an adjacent zone or element.

Therefore, I would propose to add the annotation triples `bot:interfaceOf schema:rangeIncludes bot:Element , bot:Zone .` to the definition

**Comment by maximelefrancois86** [comment]
+1

**Comment by GeorgFerdinandSchneider** [comment]
+1

**Comment by GeorgFerdinandSchneider** [comment]
As of https://github.com/w3c-lbd-cg/bot/issues/71#issuecomment-630941587 from discussion in [W3C LBD CG TelCo on 19 May 2020](https://docs.google.com/document/d/1Oi8zgtcfxyzE0c0Mfd0C2uiedl483flY_WbErHbPSes/edit#) the definition of interface of ia agreed to be changed to:

> Relationship between an interface and another thing (building zone, element or owl:Thing)

In addition the property should be annotated with 

> bot:interfaceOf schema:rangeIncludes bot:Element , bot:Zone .

where owl:Thing is implicitly in the range of the objectproperty.

With `schema:rangeIncludes` defined as a `a rdf:Property` in `<http://meta.schema.org>` ,  `schema:rangeIncludes`  should be added as an `owl:AnnotationProperty`.

**Comment by mathib** [comment]
@GeorgFerdinandSchneider: Just noticed that `bot:interfaceOf schema:rangeIncludes bot:Element , bot:Zone . ` is not yet in the BOT ontology? Should this issue be reopened?
