### ISSUE TITLE
Update definition of bot:Interface

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [w3c-lbd-cg/bot#71]
Request by @deKlerk through a comment in [LINK](https://docs.google.com/spreadsheets/d/1J5mEyblGU0M57XNpwQWxHbGlilRMzmCEqoU5FmOHILE/edit#gid=0)  to update the definition of bot:Interface:

Current definition v0.3.1:

> An interface is the surface where two building elements, two zones or a building element and a zone meet. It can be used for qualification of the connection between the two. A use case could be the qualification of the heat transmission area between a zone and a wall covering several zones. 

Suggestion by @deKlerk:

>An interface is the surface shared by two building elements, two zones or a building element and a zone. It can be used for qualification of the connection between the two. An example is the qualification of the heat transmission area between a zone and a wall covering multiple zones."

**Comment by maximelefrancois86** [comment]
I don't agree that the interface is necessarily a surface.   Topologically-wise, in general, an interface may have as spacial extent a point, a line, a surface, a volume...  
In the BOT paper on the Semantic Web Journal, we wrote: 

p7 
> A bot:Interface is a part of the world that is common to some specific zones and elements, and at the boundary of at least one of them

and 
p9 section 3.5

> The class bot:Interface is used to describe the relationship between some specific zones and elements in detail, and covers CQ6. This class can be used to qualify (i.e., attach additional information to) any of the aforementioned topological relationships between zones, elements, or zones and elements. 

http://www.semantic-web-journal.net/content/bot-building-topology-ontology-w3c-linked-building-data-group-0

**Comment by maximelefrancois86** [comment]
actually reading again what I just copy-pasted,  it is indeed necessarily a surface ^^

**Comment by GeorgFerdinandSchneider** [comment]
Summarizing the comments above:

>A bot:Interface is a part of the world with a spatial extent, that is common to some zones and elements. It allows to describe the boundary between two building elements, two zones or a building element and a zone. It can be used for qualification of the topological connections between these pairs. An example is the qualification of the heat transmission area between a zone and a wall covering multiple zones.

**Comment by mathib** [comment]
Based on discussion in LBD call of 19th of May 2020, it was proposed to make the definition of `bot:Interface` more generic.

Inserted by @GeorgFerdinandSchneider :
The discussion is available in the [minutes ](https://docs.google.com/document/d/1Oi8zgtcfxyzE0c0Mfd0C2uiedl483flY_WbErHbPSes/edit#). Most important comments received criticise the to specific definition of the previous proposal and implicit notion of two dimensional geometry.

Current adapted proposal:

> A generic concept to qualify the relationship of two or more things in the world, where at least one is a building element or zone. Examples:

We still need to decide on which examples to include. Proposals are:

- Qualification of heat transmission between zones through one or more building elements. This includes one-dimensional (surface) heat losses from one zone to another through a single building element, a two dimensional (line) loss from one zone to another through the connection in which the two elements meet or a three dimensional (point) loss from one zone to another through the connection where three elements (typically two walls and a slab) meet.
- Connection of an electric device to the electric system of a building.
- A door between one room and another.

Accordingly, the definition of `bot:interfaceOf` should be updated. Current running proposal:

> Relationship between an interface and another thing (building zone, element or something else)”

It is still unclear if `schema:rangeIncludes` can be used on `bot:interfaceOf`, pointing to `bot:Zone`, `bot:Element` and maybe a SEAS class for systems in general.

**Comment by GeorgFerdinandSchneider** [comment]
+1

I´d argue the examples should be added and also the update of schema.org/rangeIncludes statement. The revision of bot:interfaceOf is handled in https://github.com/w3c-lbd-cg/bot/issues/67
