### ISSUE TITLE
aggregates property not part of building topology

### ISSUE THREAD

**Issue by pipauwel** [w3c-lbd-cg/bot#9]
Does it make sense to have an aggregation relationship in a topology ontology? Probably not. Isn’t it the idea to keep such things in the PRODUCT ontology only? => yes!

**Comment by GeorgFerdinandSchneider** [comment]
Hi all!

I am not so sure about this.

There is two generic patterns in the description of decomposition in technical systems using the ontology-based modelling approach: **Topology** and **Mereology**.

**Mereology**

> Mereology is the theory of parthood relations (a.k.a. part-whole relations), i.e., the relations that exist between a part and the whole. [1]

Typically this modelled in this way:

> A hasPart B

where A is an aggregate and B is a part.

In BOT

> bot:Space bot:containsElement bot:Element

is a mereological relationship.

**Toplogy**

> The ontology module topology defines a theory of connectedness. It provides concepts for describing topological relations between distributed entities where there exists the possibility of emergent[...] or supervenient[...] relations between items of interest (Little and Rogova, 2005). Examples of topological relations are the connections between geographical and/or physical entities in 2D and 3D space. Moreover, the concepts of the topology module can be used to describe the connectedness of abstract entities, such as the unit operations in a process flowsheet or the activities in a business process model.

typically this is modelled similar to this:

> A isConnectedTo B
> A isDirectlyConnectedTo B

since the release v0.2.0 of BOT

> <example/interfaceA> bot:interfaceOf <example/spaceA12> .
> <example/interfaceA> bot:interfaceOf <example/wall22> .
> <example/interfaceA> rdf:type bot:Interface .

descibes a topological relationship.

**Future Development of BOT**

We might discuss in a design meeting how in future BOT should capture these two patterns. Also for ontology reuse purposes we should consider that this modelling has been undertaken in upper level ontology e.g. [dul:hasPart]( http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasPart).

[1]  J. Morbach, A. Wiesner and W. Marquardt (2007), A Meta Model for the Design of Domain Ontologies, Technical Report, No. LPT-2008-24, RWTH Aachen University, Aachen, Germany,

**Comment by GeorgFerdinandSchneider** [comment]
This is solved with v0.2.0 of BOT. However, we might keep this issue open until an example is given in README.md

E.g.:

> <example/interfaceA> bot:interfaceOf <example/spaceA12> .
> <example/interfaceA> bot:interfaceOf <example/wall22> .
> <example/interfaceA> rdf:type bot:Interface .

**Comment by GeorgFerdinandSchneider** [comment]
Solved by f14a98ad890af91ab4b68aeb3809a02142571f2f
closed()

**Comment by mathib** [comment]
Sorry to come back at this so late, but I think it could be a good idea to reintroduce `bot:aggregates` here, even if it's not really a pure topological feature. It's still similar as `bot:containsElement` which is included in BOT. We can have an alignment to `dul:hasPart` of course

The W3C LBD [upper Product ontology](https://github.com/w3c-lbd-cg/product/blob/master/prod.ttl) also mentions `product:aggregates`, but I don't know if this one should stay or be removed in favor of `bot:aggregates`. In my opinion, it's much closer to the relations described in BOT from a user perspective, so I would suggest to remove it from PRODUCT.

See also discussion here: https://github.com/w3c-lbd-cg/product/pull/12

**Comment by pipauwel** [comment]
Hi,


I am in favor of dropping the PRODUCT repository altogether, as the LBD group and charter<https://w3c-lbd-cg.github.io/lbd/charter/> seems to be in agreement that we should adopt http://schema.org/product and http://purl.org/goodrelations/ for defining product ontologies. Individual product ontologies, with e.g. OWL classes for walls, flow terminals, columns, gypsum boards, CO2 sensors, etc., are not meant to be hosted in this GIT repo, but rather in individual domain-specific standardisation organisations, such as CEN, NBN, buildingSMART, and in individual companies.


Considering the above, I am in favor of adding bot:aggregates? here in BOT as you propose.


best,

Pieter


________________________________
Van: mathib <notifications@github.com>
Verzonden: donderdag 9 mei 2019 11:06
Aan: w3c-lbd-cg/bot
CC: Pieter Pauwels; Author
Onderwerp: Re: [w3c-lbd-cg/bot] aggregates property not part of building topology (#9)


Sorry to come back at this so late, but I think it could be a good idea to reintroduce bot:aggregates here, even if it's not really a pure topological feature. It's still similar as bot:containsElement which is included in BOT. We can have an alignment to dul:hasPart of course

The W3C LBD upper Product ontology<https://github.com/w3c-lbd-cg/product/blob/master/prod.ttl> also mentions product:aggregates, but I don't know if this one should stay or be removed in favor of bot:aggregates. In my opinion, it's much closer to the relations described in BOT from a user perspective, so I would suggest to remove it from PRODUCT.

See also discussion here: w3c-lbd-cg/product#12<https://github.com/w3c-lbd-cg/product/pull/12>

-

**Comment by GeorgFerdinandSchneider** [comment]
Hi all!

interesting discussion.

I just wanted to point you to a proposed alignment with DUL which actually relates to dul:hasPart

https://github.com/w3c-lbd-cg/bot/blob/AlignmentRevision/DULAlignment.ttl

**Comment by mathib** [comment]
Missed that one! Looks good. We can add `bot:aggregates` from the moment it's back in BOT. Maybe reopen this issue so it get's visibility? We can discuss it at LDAC2019 with the group?

**Comment by pipauwel** [comment]
Discussions on the topic should take place within the LBD CG, not in an academic-industrial workshop that is external to W3C LBD (LDAC). LDAC can host some meetings and talks, but agreements need to be found among the group, which happens via the mailing list (public-lbd@w3.org), these GitHub threads, and the telco's (one coming up soon - little time).?


These GIT issues are great, but please use the mailing list as well, not everyone is notified with GIT issues. The mailing list is the W3C recommended place for discussions.



________________________________
Van: mathib <notifications@github.com>
Verzonden: donderdag 9 mei 2019 12:36
Aan: w3c-lbd-cg/bot
CC: Pieter Pauwels; Author
Onderwerp: Re: [w3c-lbd-cg/bot] aggregates property not part of building topology (#9)


Missed that one! Looks good. We can add bot:aggregates from the moment it's back in BOT. Maybe reopen this issue so it get's visibility? We can discuss it at LDAC2019 with the group?

-
